.TH BambooTracker 1 "December 15 2018"
.SH NAME
BambooTracker \- YM2608 (OPNA) tracker
.SH SYNOPSIS
.B BambooTracker
.RI " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B BambooTracker
command.
.PP
\fBBambooTracker\fP is a tracker for YM2608 (OPNA) which was used in NEC PC-8801/9801 series computers.
.SH OPTIONS
No options are supported.
.SH SEE ALSO
.BR cheesecutter (1),
.BR protracker (1),
.BR hivelytracker (1),
.BR qtractor (1),
.BR traverso (1),
.BR goattracker (1).
.br
.SH INTERNET
https://github.com/rerrahkr/BambooTracker
