.TH BambooTracker 1 "15 décembre 2018"
.SH NOM
BambooTracker \- Tracker YM2608 (OPNA)
.SH SYNOPSIS
.B BambooTracker
.RI " fichiers" ...
.br
.SH DESCRIPTION
Cette page de manuel documente rapidement la commande
.B BambooTracker
.PP
\fBBambooTracker\fP est un tracker pour le YM2608 (OPNA), qui fut utilisé dans la série d'ordinateurs NEC PC-8801/9801.
.SH OPTIONS
Aucune option n'est supportée.
.SH VOIR ÉGALEMENT
.BR cheesecutter (1),
.BR protracker (1),
.BR hivelytracker (1),
.BR qtractor (1),
.BR traverso (1),
.BR goattracker (1).
.br
.SH INTERNET
https://github.com/rerrahkr/BambooTracker
.PP
Cette page de manuel en français a été traduite par Olivier HUMBERT
.B <trebmuh@tuxfamily.org>,
pour le projet LibraZiK (mais peut être utilisée par d'autres). 
